#=========================================================================
# serverless.yml
# 
# The code of a serverless application is deployed and executed in AWS
# read this for details:
# 
# https://www.serverless.com/framework/docs/providers/aws/guide/intro
#=========================================================================
service: organostation

provider:
    name: aws
    runtime: python3.9
    stage: dev
    region: eu-central-1
    memorySize: 512
    apiGateway:
        shouldStartNameWithService: true

# extend functionality with plugins
plugins:
    - serverless-wsgi
    - serverless-python-requirements

functions:
    app:
        handler: wsgi_handler.handler
        events: # events that trigger this function
            - http: ANY /
            - http: 'ANY /{proxy+}'

custom:
    wsgi:
        app: app.app
        pythonBin: python3
        packRequirements: false

package:
    patterns:
        - '!node_modules/**'