"""Initial migration

Revision ID: 12bb4338632e
Revises: 
Create Date: 2022-08-13 14:40:45.889721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bb4338632e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('surname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('passwd', sa.String(length=128), nullable=False),
    sa.Column('project', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('passwd')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
